baseURL = '/'
languageCode = 'sl-si'
title = 'MeetPlan dokumentacija'
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

enableEmoji = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  tag = "tags"

[params]
  geekdocMenuBundle = true
  geekdocLogo = "meetplan.png"
  geekdocRepo = "https://github.com/MeetPlan/meetplan.github.io"

  [params.geekdocContentLicense]
    name = "GNU General Public License v3.0"
    link = "https://github.com/MeetPlan/meetplan.github.io/blob/main/LICENSE"
